import numpy as np
import matplotlib.pyplot as plt
from skfuzzy import membership

x = np.linspace(0, 10, num=1000)
fig, ax = plt.subplots()

gaus1 = membership.gaussmf(x, 5, 1)
gaus2 = membership.gaussmf(x, 5, 2)
gaus3 = membership.gaussmf(x, 4, 1)
ax.plot(x, gaus1, color='red', label="m=5 s=1")
ax.plot(x, gaus2, color='blue', label="m=5 s=2")
ax.plot(x, gaus3, color='green', label="m=4 s=1")
ax.legend()
ax.set_title("Gaussian Membership Function")
fig.savefig("Gaussian.pdf")

gbell1 = membership.gbellmf(x, 1, 3, 5)
gbell2 = membership.gbellmf(x, 1, 1, 5)
gbell3 = membership.gbellmf(x, 2, 1, 5)
gbell4 = membership.gbellmf(x, 1, 3, 7)
ax.plot(x, gbell1, color='red', label="a=1 b=3 c=5")
ax.plot(x, gbell2, color='blue', label="a=1 b=1 c=5")
ax.plot(x, gbell3, color='green', label="a=2 b=1 c=5")
ax.plot(x, gbell4, color='purple', label="a=1 b=3 c=7")
ax.legend()
ax.set_title("Gbell Membership Function")
fig.savefig("Gbell.pdf")

sig1 = membership.sigmf(x, 5, 3)
sig2 = membership.sigmf(x, 5, 1)
sig3 = membership.sigmf(x, 7, 3)
ax.plot(x, sig1, color='red', label="b=5 c=3")
ax.plot(x, sig2, color='blue', label="b=5 c=1")
ax.plot(x, sig3, color='green', label="b=7 c=3")
ax.legend()
ax.set_title("Sigmoid Membership Function")
fig.savefig("Sigmoid.pdf")

trap1 = membership.trapmf(x, [2, 3, 7, 8])
trap2 = membership.trapmf(x, [1, 2, 6, 7])
trap3 = membership.trapmf(x, [2, 4, 6, 9])
ax.plot(x, trap1, color='red', label="a=2 b=3 c=7 d=8")
ax.plot(x, trap2, color='blue', label="a=1 b=2 c=6 d=7")
ax.plot(x, trap3, color='green', label="a=2 b=4 c=6 d=9")
ax.legend(loc="upper right")
ax.set_title("Trapezoidal Membership Function")
fig.savefig("Trapezoidal.pdf")

tri1 = membership.trimf(x, [2, 5, 8])
tri2 = membership.trimf(x, [1, 2, 5])
tri3 = membership.trimf(x, [4, 7, 9])
ax.plot(x, tri1, color='red', label="a=2 b=5 c=8")
ax.plot(x, tri2, color='blue', label="a=1 b=2 c=5")
ax.plot(x, tri3, color='green', label="a=4 b=7 c=9")
ax.legend(loc="upper right")
ax.set_title("Triangular Membership Function")
fig.savefig("Triangular.pdf")

fig.show()
